// Generated by CoffeeScript 1.10.0
(function() {
  var ContentWrapper, PaneItem, WebComponent, str2elem,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  WebComponent = require('./web-component');

  PaneItem = require('./pane-item');

  str2elem = require('./util').str2elem;

  module.exports = ContentWrapper = (function(superClass) {
    extend(ContentWrapper, superClass);

    function ContentWrapper() {
      return ContentWrapper.__super__.constructor.apply(this, arguments);
    }

    ContentWrapper.mixin(PaneItem);

    ContentWrapper.prototype.options = {
      view: function(model) {
        var e, ref, ref1, subtle, title;
        title = ((ref = model.options) != null ? ref.title : void 0) || 'Title';
        subtle = ((ref1 = model.options) != null ? ref1.subtle : void 0) || '';
        e = str2elem("<div class=\"content-wrapper\">\n  <section class=\"content-header\">\n    <h1>" + title + " <small>" + subtle + "</small></h1>\n  </section>\n  <section class=\"content\"></section>\n</div>");
        model.manageComponentViews(e.querySelector('section.content'));
        return e;
      }
    };

    return ContentWrapper;

  })(WebComponent);

}).call(this);
