// Generated by CoffeeScript 1.10.0
(function() {
  var CompositeDisposable, Disposable, Emitter, ref;

  ref = require("event-kit"), Disposable = ref.Disposable, CompositeDisposable = ref.CompositeDisposable, Emitter = ref.Emitter;

  module.exports = {
    Disposable: Disposable,
    CompositeDisposable: CompositeDisposable,
    Emitter: Emitter
  };

}).call(this);
