// Generated by CoffeeScript 1.10.0
(function() {
  var CompositeDisposable, FormElement, WebComponent, copyProperties,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  CompositeDisposable = require('./event-kit').CompositeDisposable;

  WebComponent = require('./web-component');

  copyProperties = require('./util').copyProperties;

  FormElement = (function(superClass) {
    extend(FormElement, superClass);

    function FormElement() {
      return FormElement.__super__.constructor.apply(this, arguments);
    }

    FormElement.prototype.setModel = function(model) {
      this.model = model;
      this.model.form = new JSONEditor(this, {
        schema: this.model.options.schema
      });
      return this;
    };

    return FormElement;

  })(HTMLDivElement);

  module.exports = document.registerElement('btk-form', {
    "extends": 'div',
    prototype: FormElement.prototype
  });

}).call(this);
