// Generated by CoffeeScript 1.10.0
(function() {
  var Logo;

  Logo = (function() {
    function Logo(arg) {
      this.href = arg.href, this.mini = arg.mini, this.lg = arg.lg;
    }

    return Logo;

  })();

}).call(this);
