// Generated by CoffeeScript 1.10.0
(function() {
  var Navbar, WebComponent,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  WebComponent = require('./web-component');

  module.exports = Navbar = (function(superClass) {
    extend(Navbar, superClass);

    function Navbar() {
      return Navbar.__super__.constructor.apply(this, arguments);
    }

    return Navbar;

  })(WebComponent);

}).call(this);
