// Generated by CoffeeScript 1.10.0
(function() {
  var Page,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Page = (function(superClass) {
    extend(Page, superClass);

    function Page() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (!(this instanceof Page)) {
        return (function(func, args, ctor) {
          ctor.prototype = func.prototype;
          var child = new ctor, result = func.apply(child, args);
          return Object(result) === result ? result : child;
        })(Page, args, function(){});
      }
      Page.__super__.constructor.apply(this, args);
    }

    return Page;

  })(WebComponent);

  window.views.addViewProvider(Page, function(page) {
    var pageElement;
    pageElement = new PageElement;
    pageElement.setModel(page);
    return pageElement;
  });

  window.views.addViewProvider(Logo, function(logo) {
    var div;
    div = document.createElement('div');
    div.innerHTML = "<a href=\"" + logo.href + "\" class=\"logo\">\n  <span class=\"logo-mini\">" + logo.mini + "</span>\n  <span class=\"logo-lg\">" + logo.lg + "</span>\n</a>";
    return div.firstChild;
  });

}).call(this);
