// Generated by CoffeeScript 1.10.0
(function() {
  var CompositeDisposable, PaneView, WebComponent;

  CompositeDisposable = require('./event-kit').CompositeDisposable;

  WebComponent = require('./web-component');

  module.exports = PaneView = (function() {
    function PaneView() {}

    PaneView.prototype.setModel = function(model) {
      this.model = model;
      if (this.subscription == null) {
        this.subscription = new CompositeDisposable();
      }
      return this.subscription.add(this.model.onDidActivateItem((function(_this) {
        return function(arg) {
          var item, itemView, target;
          item = arg.item;
          itemView = WebComponent.getView(item);
          target = WebComponent.getView(_this.model);
          console.log(target);
          console.log(_this);
          if (target.hasChildNodes()) {
            return target.replaceChild(itemView, target.childNodes[0]);
          } else {
            return target.appendChild(itemView);
          }
        };
      })(this)));
    };

    return PaneView;

  })();

}).call(this);
