// Generated by CoffeeScript 1.10.0
(function() {
  var PaneItem, WebComponent,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  WebComponent = require('./web-component');

  module.exports = PaneItem = (function(superClass) {
    extend(PaneItem, superClass);

    function PaneItem() {
      return PaneItem.__super__.constructor.apply(this, arguments);
    }

    PaneItem.prototype.activateItem = function() {
      return this.container.activateItem(this);
    };

    PaneItem.prototype.onDidActivate = function(callback) {
      return this.emitter.on('did-activate', callback);
    };

    PaneItem.prototype.onDidDeactivate = function(callback) {
      return this.emitter.on('did-deactivate', callback);
    };

    return PaneItem;

  })(WebComponent);

}).call(this);
