// Generated by CoffeeScript 1.10.0
(function() {
  var CompositeDisposable, PaneElement, PaneView, WebComponent, copyProperties,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  CompositeDisposable = require('./event-kit').CompositeDisposable;

  WebComponent = require('./web-component');

  PaneView = require('./pane-view');

  copyProperties = require('./util').copyProperties;

  PaneElement = (function(superClass) {
    extend(PaneElement, superClass);

    function PaneElement() {
      return PaneElement.__super__.constructor.apply(this, arguments);
    }

    return PaneElement;

  })(HTMLDivElement);

  copyProperties(PaneView.prototype, PaneElement.prototype);

  module.exports = document.registerElement('btk-pane', {
    "extends": 'div',
    prototype: PaneElement.prototype
  });

}).call(this);
