// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  module.exports = {
    str2elem: function(string, tagName) {
      var e;
      e = document.createElement(tagName != null ? tagName : 'div');
      e.innerHTML = string;
      if (tagName == null) {
        if (e.childNodes.length === 1) {
          e = e.childNodes[0];
        }
      }
      return e;
    },
    addClasses: function() {
      var classlist, element, i, item, len, ref;
      element = arguments[0], classlist = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (i = 0, len = classlist.length; i < len; i++) {
        item = classlist[i];
        if (item instanceof Array) {
          callee.apply(null, [element].concat(slice.call(item)));
          continue;
        }
        if (typeof item === 'string') {
          item = item.trim().split(/\s+/g);
          (ref = element.classList).add.apply(ref, item);
        }
      }
      return element;
    },
    copyProperties: function(source, dest) {
      var name, value;
      for (name in source) {
        value = source[name];
        if (name === 'constructor') {
          continue;
        }
        if (!source.hasOwnProperty(name)) {
          continue;
        }
        dest[name] = value;
      }
      return dest;
    }
  };

}).call(this);
